import type { RegulatorySourceSeed } from "@mexem/shared";

/**
 * V1 registry of regulatory sources.
 *
 * NON-CRYPTO scope only. This catalog is factual — it describes what each
 * source publishes and where. Business mapping of "which obligations apply
 * to which locale" is decided downstream in ComplianceObligation records,
 * not here.
 *
 * `localeScope` = the locales a source's own publications natively target.
 * `parserKey` is forward-looking: it names the parser that *will* handle
 * this source once ingestion is built. V1 has no parsers.
 */
export const COMPLIANCE_SOURCES: RegulatorySourceSeed[] = [
  {
    code: "EUR_LEX",
    name: "EUR-Lex",
    regulator: "European Union",
    jurisdiction: "EU",
    localeScope: ["it-IT", "fr-FR", "nl-NL", "nl-BE", "fr-BE", "es-ES", "en-GB"],
    sourceType: "REGULATION",
    canonicality: "PRIMARY",
    parserKey: "eurlex-html",
    pollCadence: "weekly",
    active: true,
    baseUrl: "https://eur-lex.europa.eu",
    notes: "EU treaty, regulation, and directive corpus. Authoritative source for MiFID II (Directive 2014/65/EU) and downstream investment-marketing obligations.",
  },
  {
    code: "ESMA",
    name: "ESMA",
    regulator: "European Securities and Markets Authority",
    jurisdiction: "EU",
    localeScope: ["it-IT", "fr-FR", "nl-NL", "nl-BE", "fr-BE", "es-ES", "en-GB"],
    sourceType: "GUIDANCE",
    canonicality: "PRIMARY",
    parserKey: "esma-html",
    pollCadence: "weekly",
    active: true,
    baseUrl: "https://www.esma.europa.eu",
    notes: "EU-level guidelines, Q&As, and supervisory briefings on marketing communications under MiFID II.",
  },
  {
    code: "FCA",
    name: "FCA Handbook",
    regulator: "Financial Conduct Authority",
    jurisdiction: "GB",
    localeScope: ["en-GB"],
    sourceType: "HANDBOOK",
    canonicality: "PRIMARY",
    parserKey: "fca-handbook",
    pollCadence: "weekly",
    active: true,
    baseUrl: "https://www.handbook.fca.org.uk",
    notes: "UK FCA Handbook — primarily COBS 4 (financial promotions), including fair/clear/not-misleading requirements and prominence rules for risk warnings.",
  },
  {
    code: "AMF",
    name: "AMF",
    regulator: "Autorité des Marchés Financiers",
    jurisdiction: "FR",
    localeScope: ["fr-FR"],
    sourceType: "POSITION",
    canonicality: "PRIMARY",
    parserKey: "amf-html",
    pollCadence: "weekly",
    active: true,
    baseUrl: "https://www.amf-france.org",
    notes: "French AMF positions, recommendations, and Règlement général provisions (e.g. Article 314-10 CMF, Position DOC-2013-12 on past-performance disclaimers).",
  },
  {
    code: "AFM",
    name: "AFM",
    regulator: "Autoriteit Financiële Markten",
    jurisdiction: "NL",
    localeScope: ["nl-NL"],
    sourceType: "GUIDANCE",
    canonicality: "PRIMARY",
    parserKey: "afm-html",
    pollCadence: "weekly",
    active: true,
    baseUrl: "https://www.afm.nl",
    notes: "Dutch AFM guidance applying Wft Art. 4:19 to investment advertising — fair, clear, not misleading; accurate cost disclosure; complexity warnings.",
  },
  {
    code: "FSMA",
    name: "FSMA",
    regulator: "Financial Services and Markets Authority",
    jurisdiction: "BE",
    localeScope: ["nl-BE", "fr-BE"],
    sourceType: "CIRCULAR",
    canonicality: "PRIMARY",
    parserKey: "fsma-html",
    pollCadence: "weekly",
    active: true,
    baseUrl: "https://www.fsma.be",
    notes: "Belgian FSMA circulars and Royal Decrees covering marketing of investment products (e.g. RD 25 April 2014, Circular 2018/02 for digital/social-media advertising).",
  },
  {
    code: "CNMV",
    name: "CNMV",
    regulator: "Comisión Nacional del Mercado de Valores",
    jurisdiction: "ES",
    localeScope: ["es-ES"],
    sourceType: "CIRCULAR",
    canonicality: "PRIMARY",
    parserKey: "cnmv-html",
    pollCadence: "weekly",
    active: true,
    baseUrl: "https://www.cnmv.es",
    notes: "Spanish CNMV Circular 1/2019 and guidance — prominence parity between benefit claims and risk warnings; verbatim past-performance disclaimers.",
  },
  {
    code: "CYSEC",
    name: "CySEC",
    regulator: "Cyprus Securities and Exchange Commission",
    jurisdiction: "CY",
    localeScope: ["en-GB"],
    sourceType: "CIRCULAR",
    canonicality: "PRIMARY",
    parserKey: "cysec-html",
    pollCadence: "weekly",
    active: true,
    baseUrl: "https://www.cysec.gov.cy",
    notes: "Cypriot CySEC directives and circulars. Publishes primarily in English. Cross-border relevance (e.g. for CySEC-passported activity) is expressed downstream at the obligation level, not in localeScope.",
  },
  {
    code: "CONSOB",
    name: "CONSOB",
    regulator: "Commissione Nazionale per le Società e la Borsa",
    jurisdiction: "IT",
    localeScope: ["it-IT"],
    sourceType: "REGULATION",
    canonicality: "PRIMARY",
    parserKey: "consob-html",
    pollCadence: "weekly",
    active: true,
    baseUrl: "https://www.consob.it",
    notes: "Italian CONSOB regulations and communications on the marketing of financial products to retail investors; complements ESMA baseline domestically.",
  },
  {
    code: "HCMC",
    name: "HCMC",
    regulator: "Hellenic Capital Market Commission",
    jurisdiction: "GR",
    localeScope: ["el-GR"],
    sourceType: "CIRCULAR",
    canonicality: "PRIMARY",
    parserKey: "hcmc-html",
    pollCadence: "weekly",
    active: true,
    baseUrl: "https://www.hcmc.gr",
    notes: "Greek HCMC (Hellenic Capital Market Commission). Greece transposes MiFID II via Law 4514/2018 (art. 24 — fair, clear, not-misleading marketing communications); HCMC supplements with national circulars and public investor warnings on misleading 'guaranteed/high-return' and 'get-rich' marketing by unauthorised firms. Authoritative text ingested manually (site blocks programmatic fetch).",
  },
  {
    code: "BAFIN",
    name: "BaFin",
    regulator: "Bundesanstalt für Finanzdienstleistungsaufsicht",
    jurisdiction: "DE",
    localeScope: ["de-DE"],
    sourceType: "CIRCULAR",
    canonicality: "PRIMARY",
    parserKey: "bafin-html",
    pollCadence: "weekly",
    active: true,
    baseUrl: "https://www.bafin.de",
    notes: "German BaFin (Bundesanstalt für Finanzdienstleistungsaufsicht). Germany transposes MiFID II via the Wertpapierhandelsgesetz (WpHG, §63 ff. — information including marketing communications must be klar, redlich und nicht irreführend); BaFin supplements with national guidance (Rundschreiben/Merkblätter) and consumer warnings on misleading 'guaranteed-return' / 'get-rich' marketing. Authoritative text ingested manually.",
  },
];
