/**
 * Publisher / Market Intelligence registry — V1 curated seed data.
 *
 * Completely separate from the compliance source-of-truth layer.
 * NON-CRYPTO scope. Every source includes excludeTags/excludePaths
 * to filter out crypto/virtual-asset content from ingestion.
 *
 * Classification fields are pragmatic V1 assessments.
 * Scoring is 0–100 scale, manually assessed per source.
 * Funnel roles: awareness | research | high_intent | community | official_market
 */

import type { PublisherSourceSeed } from "@mexem/shared";

/** Default crypto-exclusion filters applied to every publisher. */
const CRYPTO_EXCLUDE_TAGS = ["crypto", "cryptocurrency", "bitcoin", "ethereum", "NFT", "DeFi", "stablecoin", "token", "blockchain", "web3", "virtual-assets", "digital-assets"];
const CRYPTO_EXCLUDE_PATHS = ["/crypto", "/criptovalute", "/criptomonedas", "/cryptocurrency", "/digital-assets", "/blockchain", "/nft", "/defi", "/web3"];

export const PUBLISHER_SOURCES: PublisherSourceSeed[] = [
  // ═══════════════════════════════════════════════════════════════════
  // ITALY
  // ═══════════════════════════════════════════════════════════════════
  {
    code: "SOLE24ORE", name: "Il Sole 24 Ore", country: "IT", localeScope: ["it-IT"], language: "it",
    sourceClass: "business_media", audienceType: "professional", ingestionMode: "rss",
    canonicalUrl: "https://www.ilsole24ore.com",
    coverageFocus: ["equities", "macro", "bonds", "funds", "listed_companies"],
    relationshipType: "reference_source", active: true,
    notes: "Italy's leading financial newspaper. Broad coverage of markets, economy, and regulation.",
    scoring: { authorityScore: 95, audienceIntentScore: 60, brandSafetyScore: 95, partnerPriority: 40, marketRelevanceScore: 85 },
    funnelRoles: ["awareness", "research"],
    includePaths: ["/finanza", "/economia", "/mercati"],
    excludeTags: CRYPTO_EXCLUDE_TAGS, excludePaths: [...CRYPTO_EXCLUDE_PATHS, "/tecnologie/blockchain"],
  },
  {
    code: "BORSA_ITALIANA", name: "Borsa Italiana", country: "IT", localeScope: ["it-IT"], language: "it",
    sourceClass: "exchange", audienceType: "active_trader", ingestionMode: "html_list",
    canonicalUrl: "https://www.borsaitaliana.it",
    coverageFocus: ["equities", "ETFs", "bonds", "listed_companies"],
    relationshipType: "reference_source", active: true,
    notes: "Milan stock exchange (Euronext). Official market data and listed instruments.",
    scoring: { authorityScore: 100, audienceIntentScore: 75, brandSafetyScore: 100, partnerPriority: 60, marketRelevanceScore: 90 },
    funnelRoles: ["official_market", "research"],
    includePaths: ["/borsa/azioni", "/borsa/etf", "/borsa/obbligazioni"],
    excludeTags: CRYPTO_EXCLUDE_TAGS, excludePaths: CRYPTO_EXCLUDE_PATHS,
  },
  {
    code: "MILANO_FINANZA", name: "Milano Finanza", country: "IT", localeScope: ["it-IT"], language: "it",
    sourceClass: "business_media", audienceType: "professional", ingestionMode: "rss",
    canonicalUrl: "https://www.milanofinanza.it",
    coverageFocus: ["equities", "macro", "funds", "listed_companies"],
    relationshipType: "reference_source", active: true,
    notes: "Italian financial daily focused on markets, asset management, and corporate finance.",
    scoring: { authorityScore: 85, audienceIntentScore: 55, brandSafetyScore: 90, partnerPriority: 35, marketRelevanceScore: 80 },
    funnelRoles: ["awareness", "research"],
    excludeTags: CRYPTO_EXCLUDE_TAGS, excludePaths: CRYPTO_EXCLUDE_PATHS,
  },
  {
    code: "CORRIERE_ECONOMIA", name: "Corriere Economia", country: "IT", localeScope: ["it-IT"], language: "it",
    sourceClass: "publisher", audienceType: "mass_market", ingestionMode: "rss",
    canonicalUrl: "https://www.corriere.it/economia",
    coverageFocus: ["macro", "education", "funds"],
    relationshipType: "reference_source", active: true,
    notes: "Economy section of Corriere della Sera. Mass-market financial coverage.",
    scoring: { authorityScore: 80, audienceIntentScore: 40, brandSafetyScore: 95, partnerPriority: 30, marketRelevanceScore: 55 },
    funnelRoles: ["awareness"],
    includePaths: ["/economia"],
    excludeTags: CRYPTO_EXCLUDE_TAGS, excludePaths: CRYPTO_EXCLUDE_PATHS,
  },
  {
    code: "WALL_STREET_ITALIA", name: "Wall Street Italia", country: "IT", localeScope: ["it-IT"], language: "it",
    sourceClass: "business_media", audienceType: "retail", ingestionMode: "rss",
    canonicalUrl: "https://www.wallstreetitalia.com",
    coverageFocus: ["equities", "ETFs", "macro", "broker_reviews"],
    relationshipType: "target_publisher", active: true,
    notes: "Italian financial portal targeting retail investors. Market analysis and broker comparisons.",
    scoring: { authorityScore: 65, audienceIntentScore: 80, brandSafetyScore: 75, partnerPriority: 80, marketRelevanceScore: 85 },
    funnelRoles: ["research", "high_intent"],
    excludeTags: CRYPTO_EXCLUDE_TAGS, excludePaths: [...CRYPTO_EXCLUDE_PATHS, "/criptovalute"],
  },
  {
    code: "SOLDIONLINE", name: "SoldiOnline", country: "IT", localeScope: ["it-IT"], language: "it",
    sourceClass: "publisher", audienceType: "retail", ingestionMode: "rss",
    canonicalUrl: "https://www.soldionline.it",
    coverageFocus: ["equities", "funds", "education", "broker_reviews"],
    relationshipType: "target_publisher", active: true,
    notes: "Italian personal finance and investing portal for retail audience.",
    scoring: { authorityScore: 55, audienceIntentScore: 85, brandSafetyScore: 75, partnerPriority: 75, marketRelevanceScore: 80 },
    funnelRoles: ["research", "high_intent"],
    excludeTags: CRYPTO_EXCLUDE_TAGS, excludePaths: CRYPTO_EXCLUDE_PATHS,
  },
  {
    code: "FINANZAONLINE", name: "FinanzaOnline", country: "IT", localeScope: ["it-IT"], language: "it",
    sourceClass: "community", audienceType: "active_trader", ingestionMode: "manual",
    canonicalUrl: "https://www.finanzaonline.com",
    coverageFocus: ["equities", "ETFs", "community", "broker_reviews"],
    relationshipType: "target_publisher", active: true,
    notes: "Italy's largest investment community forum. Active trader discussions and broker reviews.",
    scoring: { authorityScore: 45, audienceIntentScore: 90, brandSafetyScore: 60, partnerPriority: 85, marketRelevanceScore: 85 },
    funnelRoles: ["community", "high_intent"],
    excludeTags: CRYPTO_EXCLUDE_TAGS, excludePaths: [...CRYPTO_EXCLUDE_PATHS, "/forum/crypto"],
  },

  // ═══════════════════════════════════════════════════════════════════
  // SPAIN
  // ═══════════════════════════════════════════════════════════════════
  {
    code: "BOLSAMANIA", name: "Bolsamanía", country: "ES", localeScope: ["es-ES"], language: "es",
    sourceClass: "business_media", audienceType: "active_trader", ingestionMode: "rss",
    canonicalUrl: "https://www.bolsamania.com",
    coverageFocus: ["equities", "ETFs", "macro", "listed_companies"],
    relationshipType: "target_publisher", active: true,
    notes: "Spanish stock market portal with real-time data and analysis.",
    scoring: { authorityScore: 70, audienceIntentScore: 85, brandSafetyScore: 75, partnerPriority: 80, marketRelevanceScore: 85 },
    funnelRoles: ["research", "high_intent"],
    includePaths: ["/noticias", "/cotizaciones"],
    excludeTags: CRYPTO_EXCLUDE_TAGS, excludePaths: [...CRYPTO_EXCLUDE_PATHS, "/criptomonedas"],
  },
  {
    code: "ESTRATEGIAS_INV", name: "Estrategias de Inversión", country: "ES", localeScope: ["es-ES"], language: "es",
    sourceClass: "publisher", audienceType: "active_trader", ingestionMode: "rss",
    canonicalUrl: "https://www.estrategiasdeinversion.com",
    coverageFocus: ["equities", "ETFs", "funds", "education"],
    relationshipType: "target_publisher", active: true,
    notes: "Spanish investment strategies and financial education platform.",
    scoring: { authorityScore: 65, audienceIntentScore: 80, brandSafetyScore: 80, partnerPriority: 75, marketRelevanceScore: 80 },
    funnelRoles: ["research", "high_intent"],
    excludeTags: CRYPTO_EXCLUDE_TAGS, excludePaths: CRYPTO_EXCLUDE_PATHS,
  },
  {
    code: "RANKIA_ES", name: "Rankia", country: "ES", localeScope: ["es-ES"], language: "es",
    sourceClass: "community", audienceType: "retail", ingestionMode: "manual",
    canonicalUrl: "https://www.rankia.com",
    coverageFocus: ["broker_reviews", "funds", "education", "community"],
    relationshipType: "target_publisher", active: true,
    notes: "Largest Spanish-language investing community. Forum-based broker reviews and comparisons.",
    scoring: { authorityScore: 50, audienceIntentScore: 90, brandSafetyScore: 65, partnerPriority: 90, marketRelevanceScore: 90 },
    funnelRoles: ["community", "high_intent"],
    includePaths: ["/blog", "/foros/bolsa", "/foros/fondos"],
    excludeTags: CRYPTO_EXCLUDE_TAGS, excludePaths: [...CRYPTO_EXCLUDE_PATHS, "/foros/criptomonedas"],
  },
  {
    code: "FINECT", name: "Finect", country: "ES", localeScope: ["es-ES"], language: "es",
    sourceClass: "publisher", audienceType: "retail", ingestionMode: "rss",
    canonicalUrl: "https://www.finect.com",
    coverageFocus: ["funds", "ETFs", "education", "broker_reviews"],
    relationshipType: "target_publisher", active: true,
    notes: "Spanish fintech publisher. Fund comparisons, financial advisor matching.",
    scoring: { authorityScore: 55, audienceIntentScore: 85, brandSafetyScore: 80, partnerPriority: 80, marketRelevanceScore: 80 },
    funnelRoles: ["research", "high_intent"],
    excludeTags: CRYPTO_EXCLUDE_TAGS, excludePaths: CRYPTO_EXCLUDE_PATHS,
  },
  {
    code: "HELPMYCASH", name: "HelpMyCash", country: "ES", localeScope: ["es-ES"], language: "es",
    sourceClass: "publisher", audienceType: "mass_market", ingestionMode: "rss",
    canonicalUrl: "https://www.helpmycash.com",
    coverageFocus: ["education", "broker_reviews"],
    relationshipType: "target_publisher", active: true,
    notes: "Spanish personal finance comparison site. Broker and product reviews for mass-market audience.",
    scoring: { authorityScore: 45, audienceIntentScore: 75, brandSafetyScore: 80, partnerPriority: 70, marketRelevanceScore: 70 },
    funnelRoles: ["awareness", "high_intent"],
    includePaths: ["/inversiones", "/broker"],
    excludeTags: CRYPTO_EXCLUDE_TAGS, excludePaths: CRYPTO_EXCLUDE_PATHS,
  },
  {
    code: "ELECONOMISTA_ES", name: "elEconomista", country: "ES", localeScope: ["es-ES"], language: "es",
    sourceClass: "business_media", audienceType: "professional", ingestionMode: "rss",
    canonicalUrl: "https://www.eleconomista.es",
    coverageFocus: ["equities", "macro", "bonds", "listed_companies"],
    relationshipType: "reference_source", active: true,
    notes: "Major Spanish business newspaper. Broad market and economic coverage.",
    scoring: { authorityScore: 85, audienceIntentScore: 55, brandSafetyScore: 90, partnerPriority: 35, marketRelevanceScore: 80 },
    funnelRoles: ["awareness", "research"],
    includePaths: ["/mercados", "/empresas"],
    excludeTags: CRYPTO_EXCLUDE_TAGS, excludePaths: [...CRYPTO_EXCLUDE_PATHS, "/criptomonedas"],
  },
  {
    code: "EXPANSION_ES", name: "Expansión", country: "ES", localeScope: ["es-ES"], language: "es",
    sourceClass: "business_media", audienceType: "professional", ingestionMode: "rss",
    canonicalUrl: "https://www.expansion.com",
    coverageFocus: ["macro", "listed_companies", "equities"],
    relationshipType: "reference_source", active: true,
    notes: "Leading Spanish business daily (Unidad Editorial group).",
    scoring: { authorityScore: 85, audienceIntentScore: 50, brandSafetyScore: 90, partnerPriority: 30, marketRelevanceScore: 75 },
    funnelRoles: ["awareness"],
    includePaths: ["/mercados", "/empresas"],
    excludeTags: CRYPTO_EXCLUDE_TAGS, excludePaths: CRYPTO_EXCLUDE_PATHS,
  },
  {
    code: "CINCO_DIAS", name: "Cinco Días", country: "ES", localeScope: ["es-ES"], language: "es",
    sourceClass: "business_media", audienceType: "professional", ingestionMode: "rss",
    canonicalUrl: "https://cincodias.elpais.com",
    coverageFocus: ["macro", "equities", "listed_companies"],
    relationshipType: "reference_source", active: true,
    notes: "Business supplement of El País. Professional financial journalism.",
    scoring: { authorityScore: 80, audienceIntentScore: 50, brandSafetyScore: 90, partnerPriority: 30, marketRelevanceScore: 70 },
    funnelRoles: ["awareness"],
    includePaths: ["/mercados", "/empresas"],
    excludeTags: CRYPTO_EXCLUDE_TAGS, excludePaths: CRYPTO_EXCLUDE_PATHS,
  },

  // ═══════════════════════════════════════════════════════════════════
  // NETHERLANDS
  // ═══════════════════════════════════════════════════════════════════
  {
    code: "FD_NL", name: "Het Financieele Dagblad", country: "NL", localeScope: ["nl-NL"], language: "nl",
    sourceClass: "business_media", audienceType: "professional", ingestionMode: "rss",
    canonicalUrl: "https://fd.nl",
    coverageFocus: ["equities", "macro", "bonds", "listed_companies"],
    relationshipType: "reference_source", active: true,
    notes: "The Netherlands' premier financial daily. Broad market and economic coverage.",
    scoring: { authorityScore: 95, audienceIntentScore: 55, brandSafetyScore: 95, partnerPriority: 40, marketRelevanceScore: 85 },
    funnelRoles: ["awareness", "research"],
    includePaths: ["/beurs", "/economie"],
    excludeTags: CRYPTO_EXCLUDE_TAGS, excludePaths: [...CRYPTO_EXCLUDE_PATHS, "/crypto"],
  },
  {
    code: "IEX_NL", name: "IEX", country: "NL", localeScope: ["nl-NL"], language: "nl",
    sourceClass: "community", audienceType: "active_trader", ingestionMode: "rss",
    canonicalUrl: "https://www.iex.nl",
    coverageFocus: ["equities", "ETFs", "community", "broker_reviews"],
    relationshipType: "target_publisher", active: true,
    notes: "Major Dutch investing community and stock analysis platform.",
    scoring: { authorityScore: 55, audienceIntentScore: 90, brandSafetyScore: 65, partnerPriority: 90, marketRelevanceScore: 90 },
    funnelRoles: ["community", "high_intent"],
    excludeTags: CRYPTO_EXCLUDE_TAGS, excludePaths: [...CRYPTO_EXCLUDE_PATHS, "/crypto"],
  },
  {
    code: "EURONEXT_AMS", name: "Euronext Amsterdam", country: "NL", localeScope: ["nl-NL"], language: "en",
    sourceClass: "exchange", audienceType: "professional", ingestionMode: "html_list",
    canonicalUrl: "https://www.euronext.com/en/markets/amsterdam",
    coverageFocus: ["equities", "ETFs", "bonds", "listed_companies"],
    relationshipType: "reference_source", active: true,
    notes: "Amsterdam stock exchange (Euronext). Official listings and market data.",
    scoring: { authorityScore: 100, audienceIntentScore: 70, brandSafetyScore: 100, partnerPriority: 55, marketRelevanceScore: 90 },
    funnelRoles: ["official_market", "research"],
    includePaths: ["/en/markets/amsterdam"],
    excludeTags: CRYPTO_EXCLUDE_TAGS, excludePaths: CRYPTO_EXCLUDE_PATHS,
  },
  {
    code: "BNR_BEURS", name: "BNR Beurs", country: "NL", localeScope: ["nl-NL"], language: "nl",
    sourceClass: "publisher", audienceType: "retail", ingestionMode: "rss",
    canonicalUrl: "https://www.bnr.nl/podcast/beurs",
    coverageFocus: ["equities", "macro"],
    relationshipType: "reference_source", active: true,
    notes: "BNR Nieuwsradio stock market podcast. Audio/editorial market commentary.",
    scoring: { authorityScore: 70, audienceIntentScore: 60, brandSafetyScore: 90, partnerPriority: 45, marketRelevanceScore: 65 },
    funnelRoles: ["awareness"],
    excludeTags: CRYPTO_EXCLUDE_TAGS, excludePaths: CRYPTO_EXCLUDE_PATHS,
  },
  {
    code: "DE_AANDEELHOUDER", name: "De Aandeelhouder", country: "NL", localeScope: ["nl-NL"], language: "nl",
    sourceClass: "publisher", audienceType: "active_trader", ingestionMode: "rss",
    canonicalUrl: "https://www.deaandeelhouder.nl",
    coverageFocus: ["equities", "listed_companies", "education"],
    relationshipType: "target_publisher", active: true,
    notes: "Dutch shareholder and stock analysis publication for active traders.",
    scoring: { authorityScore: 60, audienceIntentScore: 80, brandSafetyScore: 80, partnerPriority: 75, marketRelevanceScore: 80 },
    funnelRoles: ["research", "high_intent"],
    excludeTags: CRYPTO_EXCLUDE_TAGS, excludePaths: CRYPTO_EXCLUDE_PATHS,
  },

  // ═══════════════════════════════════════════════════════════════════
  // FRANCE
  // ═══════════════════════════════════════════════════════════════════
  {
    code: "BOURSORAMA", name: "Boursorama Bourse", country: "FR", localeScope: ["fr-FR"], language: "fr",
    sourceClass: "business_media", audienceType: "retail", ingestionMode: "rss",
    canonicalUrl: "https://www.boursorama.com/bourse/",
    coverageFocus: ["equities", "ETFs", "funds", "broker_reviews"],
    relationshipType: "target_publisher", active: true,
    notes: "France's largest retail financial portal (SocGen-owned). Market data, analysis, broker services.",
    scoring: { authorityScore: 75, audienceIntentScore: 85, brandSafetyScore: 80, partnerPriority: 85, marketRelevanceScore: 90 },
    funnelRoles: ["research", "high_intent"],
    includePaths: ["/bourse"],
    excludeTags: CRYPTO_EXCLUDE_TAGS, excludePaths: [...CRYPTO_EXCLUDE_PATHS, "/crypto-monnaies"],
  },
  {
    code: "EURONEXT_PARIS", name: "Euronext Paris", country: "FR", localeScope: ["fr-FR"], language: "en",
    sourceClass: "exchange", audienceType: "professional", ingestionMode: "html_list",
    canonicalUrl: "https://live.euronext.com/en/markets/paris",
    coverageFocus: ["equities", "ETFs", "bonds", "listed_companies"],
    relationshipType: "reference_source", active: true,
    notes: "Paris stock exchange (Euronext). Official listings and market data.",
    scoring: { authorityScore: 100, audienceIntentScore: 65, brandSafetyScore: 100, partnerPriority: 50, marketRelevanceScore: 85 },
    funnelRoles: ["official_market", "research"],
    includePaths: ["/en/markets/paris"],
    excludeTags: CRYPTO_EXCLUDE_TAGS, excludePaths: CRYPTO_EXCLUDE_PATHS,
  },
  {
    code: "AGEFI_FR", name: "L'AGEFI", country: "FR", localeScope: ["fr-FR"], language: "fr",
    sourceClass: "business_media", audienceType: "professional", ingestionMode: "rss",
    canonicalUrl: "https://www.agefi.fr",
    coverageFocus: ["equities", "macro", "bonds", "funds"],
    relationshipType: "reference_source", active: true,
    notes: "French professional financial press. Asset management and capital markets focus.",
    scoring: { authorityScore: 85, audienceIntentScore: 50, brandSafetyScore: 90, partnerPriority: 35, marketRelevanceScore: 80 },
    funnelRoles: ["awareness", "research"],
    excludeTags: CRYPTO_EXCLUDE_TAGS, excludePaths: CRYPTO_EXCLUDE_PATHS,
  },
  {
    code: "BOURSIER_FR", name: "Boursier.com", country: "FR", localeScope: ["fr-FR"], language: "fr",
    sourceClass: "publisher", audienceType: "retail", ingestionMode: "rss",
    canonicalUrl: "https://www.boursier.com",
    coverageFocus: ["equities", "ETFs", "macro"],
    relationshipType: "target_publisher", active: true,
    notes: "French retail stock market news and analysis portal.",
    scoring: { authorityScore: 55, audienceIntentScore: 80, brandSafetyScore: 75, partnerPriority: 70, marketRelevanceScore: 75 },
    funnelRoles: ["research", "high_intent"],
    excludeTags: CRYPTO_EXCLUDE_TAGS, excludePaths: [...CRYPTO_EXCLUDE_PATHS, "/crypto"],
  },
  {
    code: "BFM_BOURSE", name: "BFM Bourse", country: "FR", localeScope: ["fr-FR"], language: "fr",
    sourceClass: "business_media", audienceType: "mass_market", ingestionMode: "rss",
    canonicalUrl: "https://www.bfmtv.com/economie/replay-emissions/bfm-bourse/",
    coverageFocus: ["equities", "macro"],
    relationshipType: "reference_source", active: true,
    notes: "BFM TV's stock market program. Mass-market financial broadcast media.",
    scoring: { authorityScore: 70, audienceIntentScore: 45, brandSafetyScore: 85, partnerPriority: 40, marketRelevanceScore: 60 },
    funnelRoles: ["awareness"],
    includePaths: ["/economie/replay-emissions/bfm-bourse", "/economie/entreprises"],
    excludeTags: CRYPTO_EXCLUDE_TAGS, excludePaths: [...CRYPTO_EXCLUDE_PATHS, "/crypto"],
  },
  {
    code: "INVESTIR_FR", name: "Investir — Les Echos", country: "FR", localeScope: ["fr-FR"], language: "fr",
    sourceClass: "publisher", audienceType: "active_trader", ingestionMode: "rss",
    canonicalUrl: "https://investir.lesechos.fr",
    coverageFocus: ["equities", "funds", "ETFs", "education"],
    relationshipType: "target_publisher", active: true,
    notes: "Investing arm of Les Echos (LVMH media group). Stock picks, fund analysis, investor education.",
    scoring: { authorityScore: 80, audienceIntentScore: 85, brandSafetyScore: 85, partnerPriority: 80, marketRelevanceScore: 85 },
    funnelRoles: ["research", "high_intent"],
    excludeTags: CRYPTO_EXCLUDE_TAGS, excludePaths: [...CRYPTO_EXCLUDE_PATHS, "/crypto-monnaies"],
  },
];
